-- MUwall Supabase schema
-- Run this once in Supabase Dashboard > SQL Editor.

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    email text,
    username text not null,
    identity text not null default 'student' check (identity in ('student', 'teacher')),
    avatar text not null default 'icon/default.png',
    major text not null default '',
    bio text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.posts (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    title text not null,
    content text not null,
    category text not null check (category in ('campus-share', 'study-help', 'daily-life', 'campus-news', 'qna')),
    author text not null,
    author_avatar text not null default 'icon/default.png',
    author_identity text not null default 'student',
    author_major text not null default '',
    author_bio text not null default '',
    like_count integer not null default 0,
    comment_count integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.post_likes (
    post_id bigint not null references public.posts(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (post_id, user_id)
);

create table if not exists public.comments (
    id bigint generated by default as identity primary key,
    post_id bigint not null references public.posts(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    content text not null check (char_length(btrim(content)) > 0),
    author text not null,
    author_avatar text not null default 'icon/default.png',
    author_identity text not null default 'student',
    author_major text not null default '',
    author_bio text not null default '',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- Older drafts sometimes created posts.user_id as bigint. Supabase Auth user ids
-- are uuid, so drop the incompatible column before adding the correct one.
do $$
begin
    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'posts'
          and column_name = 'user_id'
          and udt_name <> 'uuid'
    ) then
        alter table public.posts drop column user_id cascade;
    end if;
end;
$$;

-- If you already created older versions of these tables, these lines add the
-- columns that the current frontend expects without deleting existing data.
alter table public.profiles add column if not exists email text;
alter table public.profiles add column if not exists username text not null default 'User';
alter table public.profiles add column if not exists identity text not null default 'student';
alter table public.profiles add column if not exists avatar text not null default 'icon/default.png';
alter table public.profiles add column if not exists major text not null default '';
alter table public.profiles add column if not exists bio text not null default '';
alter table public.profiles add column if not exists created_at timestamptz not null default now();
alter table public.profiles add column if not exists updated_at timestamptz not null default now();

alter table public.posts add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.posts add column if not exists title text not null default '';
alter table public.posts add column if not exists content text not null default '';
alter table public.posts add column if not exists category text not null default 'campus-share';
alter table public.posts add column if not exists author text not null default 'User';
alter table public.posts add column if not exists author_avatar text not null default 'icon/default.png';
alter table public.posts add column if not exists author_identity text not null default 'student';
alter table public.posts add column if not exists author_major text not null default '';
alter table public.posts add column if not exists author_bio text not null default '';
alter table public.posts add column if not exists like_count integer not null default 0;
alter table public.posts add column if not exists comment_count integer not null default 0;
alter table public.posts add column if not exists created_at timestamptz not null default now();
alter table public.posts add column if not exists updated_at timestamptz not null default now();

alter table public.post_likes add column if not exists post_id bigint references public.posts(id) on delete cascade;
alter table public.post_likes add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.post_likes add column if not exists created_at timestamptz not null default now();

alter table public.comments add column if not exists post_id bigint references public.posts(id) on delete cascade;
alter table public.comments add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.comments add column if not exists content text not null default '';
alter table public.comments add column if not exists author text not null default 'User';
alter table public.comments add column if not exists author_avatar text not null default 'icon/default.png';
alter table public.comments add column if not exists author_identity text not null default 'student';
alter table public.comments add column if not exists author_major text not null default '';
alter table public.comments add column if not exists author_bio text not null default '';
alter table public.comments add column if not exists created_at timestamptz not null default now();
alter table public.comments add column if not exists updated_at timestamptz not null default now();

create index if not exists post_likes_user_id_idx on public.post_likes (user_id);
create index if not exists comments_post_id_created_at_idx on public.comments (post_id, created_at);
create index if not exists comments_user_id_created_at_idx on public.comments (user_id, created_at desc);

alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.post_likes enable row level security;
alter table public.comments enable row level security;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists posts_set_updated_at on public.posts;
create trigger posts_set_updated_at
before update on public.posts
for each row execute function public.set_updated_at();

drop trigger if exists comments_set_updated_at on public.comments;
create trigger comments_set_updated_at
before update on public.comments
for each row execute function public.set_updated_at();

create or replace function public.refresh_post_counts(target_post_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    update public.posts
    set
        like_count = (
            select count(*)::integer
            from public.post_likes
            where post_id = target_post_id
        ),
        comment_count = (
            select count(*)::integer
            from public.comments
            where post_id = target_post_id
        )
    where id = target_post_id;
end;
$$;

create or replace function public.refresh_post_counts_from_interaction()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    if tg_op in ('DELETE', 'UPDATE') then
        perform public.refresh_post_counts(old.post_id);
    end if;

    if tg_op in ('INSERT', 'UPDATE') then
        perform public.refresh_post_counts(new.post_id);
    end if;

    return coalesce(new, old);
end;
$$;

drop trigger if exists post_likes_refresh_post_counts on public.post_likes;
create trigger post_likes_refresh_post_counts
after insert or delete or update of post_id on public.post_likes
for each row execute function public.refresh_post_counts_from_interaction();

drop trigger if exists comments_refresh_post_counts on public.comments;
create trigger comments_refresh_post_counts
after insert or delete or update of post_id on public.comments
for each row execute function public.refresh_post_counts_from_interaction();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    insert into public.profiles (id, email, username, identity, avatar, major, bio)
    values (
        new.id,
        new.email,
        coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1), 'User'),
        case
            when new.raw_user_meta_data ->> 'identity' in ('student', 'teacher')
            then new.raw_user_meta_data ->> 'identity'
            else 'student'
        end,
        coalesce(new.raw_user_meta_data ->> 'avatar', 'icon/default.png'),
        coalesce(new.raw_user_meta_data ->> 'major', ''),
        coalesce(new.raw_user_meta_data ->> 'bio', '')
    )
    on conflict (id) do nothing;

    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

drop policy if exists "Profiles are readable by owner" on public.profiles;
create policy "Profiles are readable by owner"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "Users can insert own profile" on public.profiles;
create policy "Users can insert own profile"
on public.profiles
for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "Users can update own profile" on public.profiles;
create policy "Users can update own profile"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Anyone can read posts" on public.posts;
create policy "Anyone can read posts"
on public.posts
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated users can create posts" on public.posts;
create policy "Authenticated users can create posts"
on public.posts
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own posts" on public.posts;
create policy "Users can update own posts"
on public.posts
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own posts" on public.posts;
create policy "Users can delete own posts"
on public.posts
for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can read own post likes" on public.post_likes;
create policy "Users can read own post likes"
on public.post_likes
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can like posts" on public.post_likes;
create policy "Users can like posts"
on public.post_likes
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can unlike posts" on public.post_likes;
create policy "Users can unlike posts"
on public.post_likes
for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Anyone can read comments" on public.comments;
create policy "Anyone can read comments"
on public.comments
for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated users can create comments" on public.comments;
create policy "Authenticated users can create comments"
on public.comments
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "Users can update own comments" on public.comments;
create policy "Users can update own comments"
on public.comments
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can delete own comments" on public.comments;
create policy "Users can delete own comments"
on public.comments
for delete
to authenticated
using (auth.uid() = user_id);

grant select on public.comments to anon, authenticated;
grant insert, update, delete on public.comments to authenticated;
grant select on public.post_likes to authenticated;
grant insert, delete on public.post_likes to authenticated;
grant usage, select on sequence public.comments_id_seq to authenticated;

update public.posts
set
    like_count = (
        select count(*)::integer
        from public.post_likes
        where post_likes.post_id = posts.id
    ),
    comment_count = (
        select count(*)::integer
        from public.comments
        where comments.post_id = posts.id
    );
